name: Static Analytics

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analytics:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup turborepo
        uses: ./.github/actions/setup-turborepo

      - name: setup js
        uses: ./.github/actions/setup-js

      - name: Static Check
        run: na run-z build root:check,check,test
